# Site settings
title: nipy.github.io
description: "nipy.github.io"
url: "nipy.github.io"
author:
  name: "nipy"
  email: "neuroimaging@python.org"
  url: "nipy.github.io"

# Build settings
baseurl: "/nipy-jekyll/"
markdown: kramdown
source: .
destination: ./_site
permalink: "/nipy-jekyll/:title"
paginate: 8
paginate_path: /page:num/

# Custom variables
version: "1.1.0"

# Options
reverse: true

